# Generated by Django 4.1.1 on 2022-09-30 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="code_reffered",
        ),
        migrations.RemoveField(
            model_name="account",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="account",
            name="ref_active",
        ),
        migrations.RemoveField(
            model_name="account",
            name="referral_code",
        ),
    ]
