# Generated by Django 4.1.1 on 2022-10-01 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_bookborrow_options_alter_bookreturn_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="returned",
            new_name="available",
        ),
    ]
