# Generated by Django 4.1.1 on 2022-10-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_rename_returned_book_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
